name: Food Express Docker CI/CD


on:

  push:

    branches:
      - main



jobs:


  build-deploy:


    runs-on: ubuntu-latest



    steps:


    # 1. Checkout Code

    - name: Checkout Code

      uses: actions/checkout@v4



    # 2. Login Docker Hub

    - name: Login to Docker Hub

      uses: docker/login-action@v3

      with:

        username: ${{ secrets.DOCKER_USERNAME }}

        password: ${{ secrets.DOCKER_PASSWORD }}



    # 3. Build Docker Image

    - name: Build Docker Image

      run: |

        docker build \
        -t madhu934652/food-express:v1 .



    # 4. Push Image

    - name: Push Image to Docker Hub

      run: |

        docker push madhu934652/food-express:v1



    # 5. Run Container

    - name: Run Food Express Container

      run: |

        docker run -d \
        --name food-express \
        -p 3000:3000 \
        madhu934652/food-express:v1



    # 6. Wait for Application Startup

    - name: Wait for Application

      run: |

        sleep 10



    # 7. Check Container Status

    - name: Check Container

      run: |

        docker ps

        docker logs food-express



    # 8. Test API

    - name: Test Food Express API

      run: |

        curl --fail http://localhost:3000/api/menu
